### ISSUE TITLE
Very high memory consumption

### ISSUE THREAD

**Issue by claudio-benfatto** [go-graphite/carbonzipper#47]
Hello here,

we are using the `carbonzipper` version 0.7.2, in combination with the `carbonapi` (0.8.0) and `go-carbon` (0.9.1).

Our cluster is constituted by 3 nodes proxied by the `carbon-c-relay`.

We recently upgraded from an old version of the stack, and since then we are seeing a very high memory consumption pattern:

`pmap` shows  ```total         44201100K```, and `top` around `25%` usage on a very beefy server.

This is our current configuration:

`carbonzipper`
```
maxProcs: 16

timeouts:
    global: "10s"
    afterStarted: "2s"

concurrencyLimit: 0
maxIdleConnsPerHost: 100
expireDelaySec: 10
```

`carbonapi`
```
concurency: 20
cache:
   type: "mem"
   size_mb: 1024
   defaultTimeoutSec: 60

cpus: 2
tz: ""

sendGlobsAsIs: true

maxBatchSize: 1000
```

any suggestion on how to best approach the problem?

Many thanks!
